name: Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  api-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image for API tests
      - name: Build Docker image for API tests
        run: docker build -t my-api-image .

      # Run Docker container and execute API tests
      - name: Run Docker container and execute API tests
        run: docker run --rm my-api-image ./gradlew apiTest

      # Upload test results as an artifact
      - name: Upload API Test Results
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: build/results/apiTest

  web-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image for Web tests
      - name: Build Docker image for Web tests
        run: docker build -t my-web-image .

      # Run Docker container and execute Web tests
      - name: Run Docker container and execute Web tests
        run: docker run --rm my-web-image ./gradlew webTest

      # Upload test results as an artifact
      - name: Upload Web Test Results
        uses: actions/upload-artifact@v3
        with:
          name: web-test-results
          path: build/results/webTest
