name: Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  api-automation:
    runs-on: ubuntu-latest
    steps:
      # Download repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Setup Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Execute Gradle command for running API tests
      - name: Execute API Tests
        run: ./gradlew apiTest

      # Upload test results as an artifact
      - name: Upload API Test Results
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: build/results/apiTest

  web-automation:
    runs-on: ubuntu-latest
    needs: api-automation
    steps:
      # Download repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Setup Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Execute Gradle command for running web tests
      - name: Execute Web Tests
        run: ./gradlew webTest

      # Upload test results as an artifact
      - name: Upload Web Test Results
        uses: actions/upload-artifact@v3
        with:
          name: web-test-results
          path: build/results/webTest
