name: Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t my-gradle-tests-image .

      # Run Docker container for API tests
      - name: Run API tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace my-gradle-tests-image ./gradlew apiTest
          
      # Upload API test results as an artifact
      - name: Upload API Test Results
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: build/test-results/apiTest

      # Run Docker container for Web tests
      - name: Run Web tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace my-gradle-tests-image ./gradlew webTest
          
      # Upload Web test results as an artifact
      - name: Upload Web Test Results
        uses: actions/upload-artifact@v3
        with:
          name: web-test-results
          path: build/test-results/webTest
