name: Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      # Download repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-app-image:latest .

      # Run tests in Docker container
      - name: Run API Tests
        run: |
          docker run --rm my-app-image:latest ./gradlew apiTest
          
      - name: Run Web Tests
        run: |
          docker run --rm my-app-image:latest ./gradlew webTest

      # Optionally, you can upload test results if needed
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/reports
