name: Automation Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  api-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -R

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image for API Tests
        run: docker build -t my-api-tests -f src/test/java/API/Dockerfile src/test/java/API/

      - name: Run API Tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace my-api-tests ./gradlew apiTest

      - name: Upload API Test Results
        uses: actions/upload-artifact@v3
        with:
          name: api-test-results
          path: build/results/apiTest

  web-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -R

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image for Web Tests
        run: docker build -t my-web-tests -f src/test/java/Web/Dockerfile src/test/java/Web/

      - name: Run Web Tests in Docker
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace my-web-tests ./gradlew webTest

      - name: Upload Web Test Results
        uses: actions/upload-artifact@v3
        with:
          name: web-test-results
          path: build/results/webTest
